### ISSUE TITLE
Bumpers [Task list]

### ISSUE THREAD

**Issue by MutedLion74** [FRC830/2023-Tasks#70]
# Bumper [Task list]

* [ ] finish 1st set of bumpers for new/competition swerve robot
  * [x] bevel corner angle brackets holes to allow screws to be flush
  * [ ] design and build/cut bumper mounts 
  * [ ] attach numbers
* [ ] build 2nd set of bumpers
  * [ ] cut wood
  * [ ] cut corner angle brackets & drill/bevel holes
  * [ ] attach noodles
  * [ ] design and build/cut bumper mounts
  * [ ] attach numbers
* [ ] control mounting plates
