### ISSUE TITLE
Build arm [Task list]

### ISSUE THREAD

**Issue by MutedLion74** [FRC830/2023-Tasks#71]
# Arm [Task List]

* [ ] 3 sections, arms already cut need cnc.
* [ ] arm plates -> cnc now
* [ ] axle needs to be cut into 2 pieces
* [ ] gears exist -> need to find chain
* [ ] arm end pieces need bearings, hand work
* [ ] big sprochet needs cnc -> arm motor mount
