### ISSUE TITLE
Grabber [Task list]

### ISSUE THREAD

**Issue by MutedLion74** [FRC830/2023-Tasks#72]
# Grabber [Task list]

- [ ] Square tube -> cnc
- [ ] Grabbermount -> cnc
- [ ] 4 arms -> cnc
- [ ] assembly -> gears, wheels, belts, gears pnevmaticcyl 
- [ ] laser cut new wood test arms
